import { StyleSheet } from 'react-native'

import { Metrics, ApplicationStyles, Colors } from '../../shared/themes/'

export default StyleSheet.create({
  ...ApplicationStyles.screen,
  welcomeText: {
    fontSize: 20,
    color: Colors.snow,
    fontWeight: '600',
  },
  hairline: {
    borderBottomColor: Colors.snow,
    borderBottomWidth: 1,
    marginHorizontal: 20,
    marginTop: 32,
  },
  logo: {
    flex: 1,
    marginTop: Metrics.section,
    height: Metrics.images.logo,
    width: Metrics.images.logo,
    resizeMode: 'contain',
  },
  centered: {
    alignItems: 'center',
  },
  scrollView: {
    paddingBottom: Metrics.baseMargin,
    backgroundColor: 'white',
  },
  engine: {
    position: 'absolute',
    right: 0,
  },
  body: {
    backgroundColor: 'white',
  },
  sectionContainer: {
    marginTop: 32,
    paddingHorizontal: 24,
  },
  sectionTitle: {
    fontSize: 24,
    fontWeight: '600',
    color: Colors.snow,
  },
  sectionDescription: {
    marginTop: 8,
    fontSize: 18,
    fontWeight: '400',
    color: Colors.snow,
  },
  highlight: {
    fontWeight: '700',
  },
  footer: {
    color: Colors.snow,
    fontSize: 12,
    fontWeight: '600',
    padding: 4,
    paddingRight: 12,
    textAlign: 'right',
  },
  row: {
    paddingBottom: Metrics.doubleBaseMargin,
    paddingHorizontal: Metrics.doubleBaseMargin,
    flexDirection: 'row',
    marginBottom: 15,
    height: 50,
  },
  rowHost: {
    marginLeft: 15,
    marginRight: 15,
    margin: 10,
    padding: 10,
    paddingBottom: 30,
    borderRadius: 10,
    elevation: 5,
    borderRadius: 8,
    shadowColor: 'black',
    flexDirection: 'row',
    backgroundColor: Colors.greyDark,
    alignItems: 'center',
    justifyContent: 'center',
  },
  wrapper: {
    flex: 1,
    alignItems: 'center',
  },
  button: {
    flex: 1,
    height: 40,
    width: 115,
    padding: 6,
    backgroundColor: Colors.sun,
    borderColor: Colors.sun,
    borderWidth: 1,
    borderRadius: 3,
    justifyContent: 'center',
  },
  textButton: {
    textAlign: 'center',
    color: 'white',
    fontWeight: '600',
  },
  text: {
    flex: 1,
    textAlign: 'center',
    fontSize: 24,
    fontWeight: '700',
    color: Colors.greyDark,
    marginTop: 15,
  },
  textHost: {
    textAlign: 'center',
    fontSize: 30,
    fontWeight: '700',
    color: 'white',
    marginTop: 20,
  },
  textDescription: {
    fontSize: 18,
    fontWeight: '600',
    color: Colors.greyDark,
    margin: 15,
  },
  form: {
    backgroundColor: Colors.snow,
    margin: 15,
    paddingTop: 10,
    borderRadius: 10,
    shadowColor: 'black',
    shadowOpacity: 0.26,
    shadowOffset: {width: 0, height: 2},
    shadowRadius: 8,
    elevation: 5,
  },
  description: {
    height: 230,
    padding: 5,
    margin: 5,
    marginBottom: 20,
    alignItems: 'center',
  },
})
